### ISSUE TITLE
BiomeMobWeight.csv directly renamed from BiomeMobWeight.txt refuses to be recognized

### ISSUE THREAD

**Issue by Jackiecrazy** [mactso/SpawnBalanceUtility#20]
I know it is not being recognized despite the bug mentioned in #14 because I modified some values to see if it would recognize the changes, but it would not. Tried adding a dummy bat spawn to each biome in case I left any empty. Didn't work. Tried csv and CSV file extensions. Didn't work. Exported it in LibreOffice. Didn't work. Left it completely untouched. *Also* didn't work. The csv config simply refuses to be recognized. At this point I'm completely out of ideas. 
[BiomeMobWeight.csv](https://github.com/mactso/SpawnBalanceUtility/files/11233665/BiomeMobWeight.csv)

**Comment by mactso** [comment]
Because Minecraft locks all tables before presenting the world selection screen, you must completely exit and restart minecraft for changes to the CSV files to be recognized.

Changes to the TXT files are overwritten each time Minecraft is started.

So run with SBU.
Copy the TXT to CSV.
Modify the CSV (back up every half hour or so)
Start Minecraft from scratch.

Easiest test is to add minecraft:blaze to Desert and remove all other hostile mobs.  (They are easy to see at night).

**Comment by Jackiecrazy** [comment]
![2023-04-20_13 08 44](https://user-images.githubusercontent.com/6895485/233263878-f4601964-3626-416d-9229-37906e6901a0.png)
I see! Thank you.
