### ISSUE TITLE
[1.20.1] Possible incompatibility with Vampirism

### ISSUE THREAD

**Issue by MarioSMB** [mactso/SpawnBalanceUtility#23]
So... I booted up the game with this mod freshly installed and was greeted by this:  
![2023-08-02_10 36 31](https://github.com/mactso/SpawnBalanceUtility/assets/1998392/a5de3a4e-a66e-4d60-89f7-c172f53bcff7)

The hunter mob from Vampirism is spawning constantly, far beyond the game's spawn limits, causing some hefty lag!

EDIT: Just used InControl to kill them all, there were almost 4000 entities! They're spawning back really quickly.

**Comment by MarioSMB** [comment]
Fixed in latest version of the mod, thank you!

**Comment by Pootleris** [comment]
um.... i have the latest version and the same is happening... HELP

**Comment by mactso** [comment]
Oh, I'm sorry it's fixed in 1.19.4 and 1.20 but not in 1.19.2.  They made some changes to registries in 1.19.3 that prevents backwards compatibility.   I'll leave the notification turned on for the next couple weeks in case I get some time but I'm not optimistic.  I had a strong health issue last week that's reduced my productivity.  I'm having to pick and choose now.  The new medicine wipes me out about 6 hours after I take it.

**Comment by Jackiecrazy** [comment]
How was this resolved? I am encountering this issue, and I vaguely remember there being some combination of SBU and BiomeTweaker that solved it, but I don't recall anymore.

**Comment by Jackiecrazy** [comment]
For those looking, set the hunters' spawn weight to 0. They will still spawn, but at a normal rate.

**Comment by mactso** [comment]
Thanks!   I was very sick from august to september.  hospitalized twice.  still not back to normal.   Thanks for posting the spawnweight tip!   yes, Vampirism is hard-coded to 0.  I changed the mod back then to where it would keep those lines.
